services:
  backend:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    environment:
      DB_HOST: postgres
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: hackathon_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hackathon_db
      POSTGRES_USER: hackathon_user
      POSTGRES_PASSWORD: hackathon_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hackathon_user -d hackathon_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
